<a href="https://colab.research.google.com/github/Favourwendee/Fast-Food-Simulation-Program/blob/main/Fast_Food_Simulator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Section 1: Data loading and manipulation

About dataset
1. `menu.csv`: A table that shows the code to be entered in the fast food menu item keyboard to get a certain food. It also contains the amount of products available. The file can be read from this address: https://www.dropbox.com/s/aer7yfyzrd6yog5/menu.csv?raw=1

2. `foods.csv`: A table with the name of each food (without capitalisation), the category and the price. The file can be read from this address: https://www.dropbox.com/s/ln97rid8o3bdh1h/foods.csv?raw=1

By running the following code cells, the two files are printed as pandas data frames:

In [ ]:
# import required python modlues
import pandas as pd
from getpass import getpass
import time
import pandas as pd
import numpy as np

In [ ]:
# programatically download and read the menu files
menu = pd.read_csv('https://www.dropbox.com/s/aer7yfyzrd6yog5/menu.csv?raw=1')
menu

   menu_number             food  amount
0           A1       Margherita     8.0
1           A2        Pepperoni     5.0
2           A3              NaN     NaN
3           A4              NaN     NaN
4           B1          Big Mac     6.0
5           B2  Halloumi Burger     3.0
6           B3              NaN     NaN
7           B4              NaN     NaN
8           C1              NaN     NaN
9           C2            Gyoza     7.0
10          C3            Ramen     4.0
11          C4         Yakisoba     5.0
12          D1              NaN     NaN
13          D2     Glazed Donut     8.0
14          D3              NaN     NaN
15          D4              NaN     NaN

In [ ]:
# programatically download and read the foods files
foods = pd.read_csv('https://www.dropbox.com/s/ln97rid8o3bdh1h/foods.csv?raw=1')
foods

                             food category  price
0             jomino's margherita    pizza   5.50
1              jomino's pepperoni    pizza   6.75
2              mctonald's big mac   burger   4.25
3                   fitsu's gyoza  dim sum   5.00
4                   fitsu's ramen  dim sum   7.52
5  burger queen's halloumi burger   burger   5.10
6            hey sushi's yakisoba  dim sum   8.23
7     crispy creme's glazed donut   sweets   1.25

### Section 2: Standardising the column names

The food names are not written exactly in the same on both data frames! Most notably, you can see that in the `foods` data frame the foods have the brand before the food name, whereas in the `menu` data frame the foods are capitalised and do not have the brand name before. Therefore, you need to create and **apply** a function which cleans the `food` entries of the `foods` data frame to make them look **the same way** as in the `menu` data frame!

In [ ]:
## define function to standardise the product names in the "foods" data frame
def change_name(x):
  ## the product names were split to separate the brand name from the food name, using "('s)", since it ends all the brand names.
    x[['item_1','item_2']]=x['food'].str.split("'s ",expand=True)
    #takes the food names and uses the title() function to capitalize each word in the food names.
    x['food'] = x['item_2'].str.title()
    # drops the brand names, leaving only the food names in the desired format
    x.drop(['item_1','item_2'], axis=1, inplace=True)


## apply the change_name function to the "foods" data frame to standardize the product names
change_name(foods)
# display the standardized "foods" data frame
foods

              food category  price
0       Margherita    pizza   5.50
1        Pepperoni    pizza   6.75
2          Big Mac   burger   4.25
3            Gyoza  dim sum   5.00
4            Ramen  dim sum   7.52
5  Halloumi Burger   burger   5.10
6         Yakisoba  dim sum   8.23
7     Glazed Donut   sweets   1.25

### Section 3: Merging the Datasets

Once that both columns look the same, you need to **merge** them as a single data frame so that this can be used in the program.

*Hint:* The merged data frame can have `menu_number` as the index, and all the information from the `foods` data frame next to each product.

In [ ]:
## merge the menu dataframe and the foods dataframe using a common column 'food'
df_merge = pd.merge(menu,
                       foods,
                       how = 'left', on = ['food'])
# set menu_index to be the index and used inplace to set the changes permanently
df_merge.set_index("menu_number", inplace=True)
# display result in required format
df_merge

                        food  amount category  price
menu_number
A1                Margherita     8.0    pizza   5.50
A2                 Pepperoni     5.0    pizza   6.75
A3                       NaN     NaN      NaN    NaN
A4                       NaN     NaN      NaN    NaN
B1                   Big Mac     6.0   burger   4.25
B2           Halloumi Burger     3.0   burger   5.10
B3                       NaN     NaN      NaN    NaN
B4                       NaN     NaN      NaN    NaN
C1                       NaN     NaN      NaN    NaN
C2                     Gyoza     7.0  dim sum   5.00
C3                     Ramen     4.0  dim sum   7.52
C4                  Yakisoba     5.0  dim sum   8.23
D1                       NaN     NaN      NaN    NaN
D2              Glazed Donut     8.0   sweets   1.25
D3                       NaN     NaN      NaN    NaN
D4                       NaN     NaN      NaN    NaN

### Section 5: Changing values in a data frame

Oops! I forgot to add three Chips in B4! Can you add them to the data frame please?

In [ ]:
## Use this cell to add three units of Chips to slot B4, output should look like this
# Added the product name 'Chips' to the menu_index 'B4', and gave it an amount of 3.0, category belonging to 'side' and a price of 3.00
df_merge.loc['B4'] = 'Chips', 3.0, 'side', 3.00
# display result in required format
df_merge

                        food  amount category  price
menu_number
A1                Margherita     8.0    pizza   5.50
A2                 Pepperoni     5.0    pizza   6.75
A3                       NaN     NaN      NaN    NaN
A4                       NaN     NaN      NaN    NaN
B1                   Big Mac     6.0   burger   4.25
B2           Halloumi Burger     3.0   burger   5.10
B3                       NaN     NaN      NaN    NaN
B4                     Chips     3.0     side   3.00
C1                       NaN     NaN      NaN    NaN
C2                     Gyoza     7.0  dim sum   5.00
C3                     Ramen     4.0  dim sum   7.52
C4                  Yakisoba     5.0  dim sum   8.23
D1                       NaN     NaN      NaN    NaN
D2              Glazed Donut     8.0   sweets   1.25
D3                       NaN     NaN      NaN    NaN
D4                       NaN     NaN      NaN    NaN

## Section 6: Fast-Food Simulation Program

Once that you have generated your merged dataset, you will use the following code cell to write a small program with the following *four* options:

1. **Admin login**: This option will simulate how the fast-food operator validates their credentials. When this option is selected, the user should be prompted to input their username and password. The username should be *admin* and the password should be any number smaller than *10* (including float and negative numbers). You should allow the user to try *four* times, if all of them are incorrect, then the program stops and the program cell needs to be run again.

  * Note: Once that an admin has logged in, this option has to be disabled (i.e. the user cannot go back and select this option).

2. **Add products**: This option can only be accessed once option 1 has been completed, otherwise the message *login first!* should be displayed and the program should go back to the main menu. In this option, the admin will be shown the list of foods and categories in the fast-food menu. Then, the admin can input a menu number  to add *one more product* for that certain menu slot. Afterwards, the program should show the new foods and go back to the main menu.
  
  * Note: Keep in mind that each space in the fast-food menu can hold a maximum of *eight* products (of the same food, of course). Also, you cannot add products in the empty menu slots. Therefore, your program should warn the admin in case that they want to add more products of a specific food in a menu slot, or if the admin wants to add products in an empty slot.

3. **Buy food**: This option can be accessed by "anyone", so there is no need for a validation. If this option is selected, the user will be shown the list of foods, amounts and prices. Then, the user will be requested to select one food item based on the `menu_number`. Once the food is selected, your program must display the price of the selected product. Then, the user will be prompted to pay. To simulate this payment, you will ask the user for an input and write any positive number (if the user inputs something invalid, ask to try again). Then, your program must check this number against the price of the product to be bought. If the input number is larger than the price, then you should return *your change is...* and the subtraction of the payment minus the price of the snack. If the number is equal to the price, then you must return *thanks for paying*. Else, you should output *you need to pay more* and allow the user to write another amount. After the "purchase", you should output to the user the number of products left for that particular food (therefore, you need to update the data frame!). Notice that if there were zero products left for the food selected, then you must prompt this to the user in advance before letting them buy, and ask them to select another food.

4. **Exit**

In [ ]:
## Use this cell to write your code
# loop = True
# while loop == True:
#   print('Welcome to the RGyUm fast-food menu. Select an option:')
#   print('1. Log in (admin only)')
#   print('2. Add one more product of a certain food (admin only)')
#   print('3. Buy products')
#   print('4. Exit')
#   # then you ask the user for options

# import python modules to be use
import string
import time
import pandas as pd
import numpy as np
from getpass import getpass

data = df_merge

admin = {'authenticated':False}

# login required decorator
def login_required(func):
    def wrapper():
        # checks if the user is login, if  not tells the user to login first
        if not admin['authenticated']:
            print_pause("You need to login first!")
            open_portal()
        # if user is logged in, redirects the user to the next route
        else:
            func()
    return wrapper

# simulate typewritter
def typewriter_simulator(message, delay=0.01):
    for char in message:
        print(char, end='', flush=True)
        time.sleep(delay)
        if char in string.punctuation:
            time.sleep(0.2)
    print('')

def print_pause(message, delay=0.5):
    typewriter_simulator(message)
    time.sleep(delay)

# validate input
def validate_input(prompt, options):
    # loop to continually request a valid input from user
    while True:
        # Handles exceptions and error that might cause the system to crash
        try:
            option = input(prompt)
            # if the user's choice is invalid, outputs Invalid Input then prompts the user to re-enter another valid input
            if option not in options:
                print_pause("Invalid Input")
            # checks if the user input is 4 i.e exit the program
            elif option == '4':
                exit_portal()
            else:
                return option
        except (ValueError, TypeError):
            pass

# validate login
def validate_login(username, password):
    # checks if the username is equal to  and password ranges from negative infinity to 10
    if username == 'admin' and password <= 10.0:
        # if the previous two checks are true, it changes the admin authentication status to true
            # and redirects the user to the food portal
        admin['authenticated'] = True
        print_pause("Login Successful")
        food_portal()
        #  if the user inputs wrong username and/or password, it prompts the user to retry
    else:
        print_pause("Invalid username or password")

# login user
def login():
    # initializes the number of user login trial to 0
    login_attempts = 0
    # allows the user to try for 4 times
    while login_attempts < 4:
        print_pause("Accessible to only Admins")
        # for every unsuccessful login attempt, the round is incremented by 1 till it reaches 4 times
        login_attempts += 1
        # handles all exceptions and errors that might cause the program to crash
        try:
            username = input("Username: ")
            # getpass() python's inbuilt function is used to hide the user's password for others to see
            password = float(getpass())
            validate_login(username, password)
        except (ValueError, TypeError):
            pass

    # if the number of login attempts reaches 4 times, the program exits by itself
    exit_portal()

# validates the admin's choice of food based on menu_number
def validate_product(prompt, options):
    # loop to continually request a valid input from user
    while True:
        # handles all exceptions and errors that might cause the program to crash
        try:
            option = str(input(prompt))
            # checks if the user's choice exist in the options passed across the validate_product function
            if option in options:
                #  displays the user's choice menu_number and food
                print_pause(f"{str(option)} - {data.loc[str(option)]['food']}")
                # prevents the user from updating the empty menu slots
                if option in data[data.isnull().any(axis=1)].index:
                    print_pause("Please enter a menu number that doesn't contain NaN")
                # selects all the food products which do not contain empty menu slots
                elif option in data[~data.isnull().any(axis=1)].index:
                    # requests the amount of food that the user would like to add
                    food_amount = int(input(f"What amount of {data.loc[str(option)]['food']} would you like to add?\nNote: A menu can only hold a maximum of 8 products.\n"))
                    if food_amount > 0:
                        # sums the amount the user want to add to the existing amount in the database
                        total_amount = food_amount + data.loc[str(option)]['amount']
                        # checks to make sure that the total amount is not above 8
                        if total_amount <= 8:
                            # hecks to make sure that the total amount is not less than or equal to 0
                            if total_amount <= 0:
                                print_pause("Sorry, a menu's amount cannot be less than 1")
                            # if the total amount falls between 1 and 8, it updates the amount in the database table and returns
                            # the current amount for the food menu and redirects the user to the food portal page
                            else:
                                data.loc[str(option), 'amount'] = total_amount
                                print_pause(f"{food_amount} amount of food was added to {data.loc[str(option)]['food']} menu, making a total of {data.loc[str(option)]['amount']}")
                                food_portal()
                        # if the total amount is above 8, it prompts the user that a menu can only hold a maximum of 8 products
                        elif total_amount > 8:
                            print_pause(f"Unable to add {food_amount} amount of food, because {data.loc[str(option)]['food']} is full")
                            # break
                    # handles invalid input
                    else:
                        print_pause('Amount should be greater than 0')
                # if the user input amount is less than or equal to 0, it prompts the user that the amount should be greater than 0
                else:
                    break
            # if user inputs a menu number that doesn't exit, it requests the user to re-input a valid menu number
            else:
                print_pause("This menu number does not exist")
        except (ValueError, TypeError):
            print_pause("Invalid input")

# validates the user's choice of food based on menu_number
def validate_order(prompt, options):
 #     loop to continually request a valid input from user
    while True:
#          handles all exceptions and errors that might cause the program to crash
        try:
            option = input(prompt)
#             checks if the user's choice menu is available
            if isinstance(option, str):
#         checks if the user's choice exist in the options passed across the validate_order function
                if option in options and data.loc[str(option)]['amount'] >= 1:
                    print_pause(f"{str(option)} - {data.loc[str(option)]['food']} costs {data.loc[str(option)]['price']} ")
             #     loop to continually request a valid input from user
                    while True:
#                         handles all exceptions and errors that might cause the program to crash
                        try:
#                             reuquest the user to make payment
                            checkout = float(input('Kindly make payment \n'))
#                             checks if the amount paid is greater than 0
                            if checkout > 0:
#                               checks if the amount paid is equal to the cost of the food product
                                if checkout == data.loc[str(option)]['price']:
                                    print_pause('Thanks for paying')
                                    finalize(option)
#                                 checks if the amount paid is greater than the cost of the food product and returns change back to the user
                                elif checkout > data.loc[str(option)]['price']:
                                    change = checkout - data.loc[str(option)]['price']
                                    print_pause(f"{checkout} - {data.loc[str(option)]['price']} = {round(change,3)} \n Your change is {round(change,3)}")
                                    finalize(option)
#                                 checks if the amount paid is less than the cost of the food product, and requests for more cash from the user
                                else:
                                    pay_more = data.loc[str(option)]['price'] - checkout
                                    print_pause(f"{data.loc[str(option)]['price']} - {checkout} = {round(pay_more,3)} \n You need to pay more {round(pay_more,3)} to purchase {data.loc[str(option)]['food']}")
                                    # pay_more(checkout)
                                    while True:
                                    #           reuquest the user to make payment
                                        more = float(input('Kindly balance up to make purchase \n'))
                                        new_pay = checkout + more
                                        # handles all exceptions and errors that might cause the program to crash
                                        try:
                                            # checks if the amount paid is greater than 0
                                            if new_pay > 0:
                                                # checks if the amount paid is equal to the cost of the food product
                                                if new_pay == data.loc[str(option)]['price']:
                                                    print_pause('Thanks for paying')
                                                    finalize(option)
                                #               checks if the amount paid is greater than the cost of the food product and returns change back to the user
                                                elif new_pay > data.loc[str(option)]['price']:
                                                    change = new_pay - data.loc[str(option)]['price']
                                                    print_pause(f"{new_pay} - {data.loc[str(option)]['price']} = {round(change,3)} \nYour change is {round(change,3)}")
                                                    finalize(option)
                                #               checks if the amount paid is less than the cost of the food product, and requests for more cash from the user
                                                elif new_pay < data.loc[str(option)]['price']:
                                                    pay_more = data.loc[str(option)]['price'] - new_pay
                                                    print_pause(f"{data.loc[str(option)]['price']} - {new_pay} = {round(pay_more,3)} \nYou need to pay more {round(pay_more,3)} to purchase this {data.loc[str(option)]['food']}")
                                                    checkout = new_pay
                                                else:
                                                    print_pause('')
                                #           if the user inputs an invalid choice for payment
                                            else:
                                                print_pause('Invalid Input jjala')
                                        except (ValueError, TypeError):
                                            print_pause('Invalid Input jkksja')
                                            pass

                            else:
                                print_pause('Input a valid number')

                        except (ValueError, TypeError):
                            print_pause('Invalid Input djsdj')
                            pass
#                 handles and event in which the user keeps buying a particular food till it finishesdisplays that the menu is finished
                else:
                    print_pause('Menu is not available or Invalid input. \n Please try again')
#              displays that the menu is finished
            else:
                ValueError('Invalid input. Please enter a valid Menu_number')
        except ValueError as error:
            print_pause(error)


# once the payment is successful, this displays the updated menu, buy substracting 1 amount from the food amount and displays the current food amount
def finalize(option):
    amount = data.loc[str(option)]['amount']
    if amount >= 1:
        data.loc[str(option), 'amount'] = amount - 1
        print_pause(f"{data.loc[str(option)]['food']} now has only {amount - 1}")
        food_portal()
    else:
        print_pause('This food has finished. Please select another food.')
        buy_products()

# The Food Portal
def open_portal():
    options = [
        '1. Log in (admin only)',
        '2. Add one more product of a certain food (admin only)',
        '3. Buy products',
        '4. Exit'
    ]

    for option in options:
        print_pause(option)
    #   requests the user's input and validate's it
    user_choice = int(validate_input("(Please enter 1, 2, 3, or 4).\n", ['1', '2', '3', '4']))
    #   '1. Log in (admin only)'
    if user_choice == 1:
        #  checks if the user is logged in
        if admin['authenticated']:
            print_pause("Unable to access this page because you are already logged in.")
        # if user not logged in directs the user to login
        else:
            login()
    # '2. Add one more product of a certain food (admin only)'
    elif user_choice == 2:
        add_product()
    # '3. Buy products'
    elif user_choice == 3:
        buy_products()


# decorator to check if user is logged in
@login_required
# add products
def add_product():
#     display all the food available to the admin
    print(data)
    print_pause('Add one or more products to a menu slot')
    menu_slot = validate_product('What Menu would you like to add? Select based on menu_number \n', data.index)

# buy products
def buy_products():
#     prints all the food menu that do not contain empty slots to the user
    print_pause('What would you like to buy? We have the following')
    print(data[~data.isnull().any(axis=1)])
    menu_order = validate_order("(Please select one food item based on the menu_number). \n", data.index)

# Function that quits the food portal
def exit_portal():
    print_pause("We would love to have you again!")
    print_pause('Thanks for visiting! Goodbye!')
    exit(0)

# Function that begins opens the food portal console
def food_portal():
    print_pause('Welcome to the RGyUm fast-food menu.')
    print_pause('Select an option: ')

    # Infinite loop.
    while True:
        open_portal()


# Initialize the portal
if __name__ == '__main__':
    food_portal()

Welcome to the RGyUm fast-food menu.
Select an option:
1. Log in (admin only)
2. Add one more product of a certain food (admin only)
3. Buy products
4. Exit
(Please enter 1, 2, 3, or 4).
2
You need to login first!
1. Log in (admin only)
2. Add one more product of a certain food (admin only)
3. Buy products
4. Exit
(Please enter 1, 2, 3, or 4).
1
Accessible to only Admins
Username: admin
········
Accessible to only Admins
Username: admin
········
Login Successful
Welcome to the RGyUm fast-food menu.
Select an option:
1. Log in (admin only)
2. Add one more product of a certain food (admin only)
3. Buy products
4. Exit
(Please enter 1, 2, 3, or 4).
1
Unable to access this page because you are already logged in.
1. Log in (admin only)
2. Add one more product of a certain food (admin only)
3. Buy products
4. Exit
(Please enter 1, 2, 3, or 4).
2
                        food  amount category  price
menu_number
A1                Margherita     8.0    pizza   5.50
A2                 Pepperoni     5.0    pizza   6.75
A3                       NaN     NaN      NaN    NaN
A4                       NaN     NaN      NaN    NaN
B1                   Big Mac     6.0   burger   4.25
B2           Halloumi Burger     3.0   burger   5.10
B3                       NaN     NaN      NaN    NaN
B4                     Chips     3.0     side   3.00
C1                       NaN     NaN      NaN    NaN
C2                     Gyoza     7.0  dim sum   5.00
C3                     Ramen     4.0  dim sum   7.52
C4                  Yakisoba     5.0  dim sum   8.23
D1                       NaN     NaN      NaN    NaN
D2              Glazed Donut     8.0   sweets   1.25
D3                       NaN     NaN      NaN    NaN
D4                       NaN     NaN      NaN    NaN
Add one or more products to a menu slot
What Menu would you like to add? Select based on menu_number
A1
A1 - Margherita
What amount of Margherita would you like to add?
Note: A menu can only hold a maximum of 8 products.
2
Unable to add 2 amount of food, because Margherita is full
What Menu would you like to add? Select based on menu_number
B4
B4 - Chips
What amount of Chips would you like to add?
Note: A menu can only hold a maximum of 8 products.
2
2 amount of food was added to Chips menu, making a total of 5.0
Welcome to the RGyUm fast-food menu.
Select an option:
1. Log in (admin only)
2. Add one more product of a certain food (admin only)
3. Buy products
4. Exit